ALTER TABLE requests ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE requests ADD COLUMN IF NOT EXISTS payment_amount NUMERIC DEFAULT 0;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
