// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Redirect to our local PostgREST instance or production API
const envUrl = import.meta.env.VITE_SUPABASE_URL || 'http://localhost:3000';
const SUPABASE_URL = typeof envUrl === 'string' && envUrl.startsWith('http') ? envUrl : `${window.location.origin}${envUrl}`;
// Dummy key since PostgREST relies on JWT
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'dummy';

// Вспомогательные функции для работы с сессией в localStorage и sessionStorage
export const getAuthToken = (): string | null => {
  return localStorage.getItem('auth_token') || sessionStorage.getItem('auth_token');
};

export const getAuthUser = (): string | null => {
  return localStorage.getItem('user') || sessionStorage.getItem('user');
};

export const clearAuth = () => {
  console.log('[Supabase Client] Очистка токенов и сессий авторизации...');
  localStorage.removeItem('auth_token');
  localStorage.removeItem('user');
  sessionStorage.removeItem('auth_token');
  sessionStorage.removeItem('user');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (input, options) => {
      // Подменяем пути Supabase API на пути локального PostgREST
      // supabase-js передаёт сюда URL, а не строку. В таком случае прежняя
      // проверка не срабатывала и запрос уходил на /api/rest/v1/... вместо
      // /api/..., что PostgREST отвечает 404.
      const requestUrl =
        typeof input === 'string'
          ? input
          : 'url' in input
            ? input.url
            : input.href;
      // Подменяем путь Supabase REST на путь PostgREST
      const url = requestUrl.replace('/rest/v1/', '/');
      // Вспомогательный токен авторизованного пользователя
      const token = getAuthToken();
      options = options || {};

      // Нормализуем объект заголовков: собираем служебные заголовки (Prefer, Range, Accept, etc.)
      const headersObj: Record<string, string> = {};

      const appendHeader = (k: string, v: string) => {
        const lowerKey = k.toLowerCase();
        // Полностью исключаем дубликаты заголовков авторизации и apikey от старого SDK
        if (lowerKey === 'authorization' || lowerKey === 'apikey') {
          return;
        }
        headersObj[k] = v;
      };

      // Извлекаем заголовки из options.headers
      if (options.headers instanceof Headers) {
        options.headers.forEach((value, key) => appendHeader(key, value));
      } else if (options.headers && typeof options.headers === 'object') {
        for (const [k, v] of Object.entries(options.headers)) {
          if (typeof v === 'string') appendHeader(k, v);
        }
      }

      // Извлекаем заголовки из input.headers (если input это Request)
      if (input && typeof input === 'object' && 'headers' in input && (input as any).headers) {
        const reqHeaders = (input as any).headers;
        if (reqHeaders instanceof Headers) {
          reqHeaders.forEach((value, key) => appendHeader(key, value));
        } else if (typeof reqHeaders === 'object') {
          for (const [k, v] of Object.entries(reqHeaders)) {
            if (typeof v === 'string') appendHeader(k, v);
          }
        }
      }

      // Очищаем токен авторизации от возможного префикса 'Bearer '
      let cleanToken = (token || '').trim();
      if (cleanToken.toLowerCase().startsWith('bearer ')) {
        cleanToken = cleanToken.slice(7).trim();
      }

      // Проверяем: JWT токен валиден, если он состоит ровно из 3-х частей, разделенных точками (header.payload.signature)
      const tokenParts = cleanToken.split('.');
      if (cleanToken && cleanToken !== 'dummy' && cleanToken !== 'undefined' && cleanToken !== 'null' && tokenParts.length === 3) {
        // Устанавливаем ЕДИНСТВЕННЫЙ заголовок Authorization
        headersObj['Authorization'] = `Bearer ${cleanToken}`;
        console.log(`[Supabase Client] Запрос к API авторизован токеном JWT (3 части)`); // Логирование авторизации
      } else {
        // Если пользователь не авторизован или токен невалиден — запрос отправляется БЕЗ заголовка Authorization
        // PostgREST гарантированно обрабатывает его от встроенной роли анонима anon (PGRST_DB_ANON_ROLE)
        delete headersObj['Authorization'];
        delete headersObj['authorization'];
        console.log(`[Supabase Client] Анонимный запрос к API без заголовка Authorization (роль anon)`); // Логирование анонимного доступа
      }

      // Извлекаем HTTP-метод запроса (по умолчанию GET)
      const method = options.method || (input && typeof input === 'object' && 'method' in input ? (input as any).method : 'GET');

      // Применяем очищенные заголовки и метод
      options = {
        ...options,
        method,
        headers: headersObj,
      };

      return fetch(url, options);
    }
  }
});

// Polyfill for session checking so components don't crash when using supabase.auth.getSession()
const authPolyfill = {
  getSession: async () => {
    const token = getAuthToken();
    const userStr = getAuthUser();
    if (token && userStr) {
      return { data: { session: { access_token: token, user: JSON.parse(userStr) } }, error: null };
    }
    return { data: { session: null }, error: null };
  },
  getUser: async () => {
    const userStr = getAuthUser();
    if (userStr) {
      return { data: { user: JSON.parse(userStr) }, error: null };
    }
    return { data: { user: null }, error: null };
  },
  onAuthStateChange: (callback: any) => {
    // Слушатель кастомного события изменения авторизации
    const handler = () => {
      const token = getAuthToken();
      const userStr = getAuthUser();
      let session = null;
      if (token && userStr) {
        session = { access_token: token, user: JSON.parse(userStr) };
      }
      console.log('[Supabase Auth] Получено событие auth-change, уведомляем слушателей о смене сессии...'); // Логирование
      callback('SIGNED_IN', session);
    };

    // Регистрируем глобальный слушатель события
    window.addEventListener('auth-change', handler);

    // Первоначальное уведомление о сессии при монтировании (INITIAL_SESSION)
    const token = getAuthToken();
    const userStr = getAuthUser();
    let session = null;
    if (token && userStr) {
      session = { access_token: token, user: JSON.parse(userStr) };
    }
    setTimeout(() => {
      if (callback) {
        console.log('[Supabase Auth] Первоначальное уведомление о сессии INITIAL_SESSION...'); // Логирование
        callback('INITIAL_SESSION', session);
      }
    }, 0);

    // Возвращаем объект отписки
    return {
      data: {
        subscription: {
          unsubscribe: () => {
            console.log('[Supabase Auth] Отписка от событий auth-change'); // Логирование
            window.removeEventListener('auth-change', handler);
          }
        }
      }
    };
  },
  signOut: async () => {
    console.log('[Supabase Auth] Вызов signOut, очищаем localStorage/sessionStorage и генерируем событие auth-change...'); // Логирование
    clearAuth();
    // Генерируем событие для мгновенного реактивного обновления во всех компонентах
    window.dispatchEvent(new Event("auth-change"));
    return { error: null };
  }
};

Object.assign(supabase.auth, authPolyfill);
